#!/bin/bash -l
#SBATCH --job-name=abaTest
#SBATCH --error=%j.err
#SBATCH --output=%j.out
#SBATCH --nodes=1
#SBATCH --ntasks=10
#SBATCH --time=00:15:00
#SBATCH --partition=test
#SBATCH --account=<your_project>

# This script runs in parallel Abaqus example e1 on Puhti server using 10 core.
# Before using this script, fill <your_project> and <your_run_directory>

unset SLURM_GTIDS

module load abaqus/2022

cd <your_run_directory>

abq2022 job=e1.inp fetch

mkdir tmp_$SLURM_JOB_ID

abq2022 job=e1 cpus=$SLURM_NTASKS -verbose 2 standard_parallel=all scratch=tmp_$SLURM_JOB_ID interactive

