#!/bin/bash -l
# Author: Xuan Binh 春平
#SBATCH --job-name=abaArrayTest
#SBATCH --output=%j.out
#SBATCH --error=%j.err
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=10
#SBATCH --mem-per-cpu=1G
#SBATCH --array=1-2
#SBATCH --time=01:00:00
#SBATCH --partition=small
#SBATCH --account=project_2007935
#SBATCH --mail-type=ALL
#SBATCH --mail-user=binh.nguyen@aalto.fi

#
# This example batch job file runs two Abaqus analysis in array mode, see the docs
# https://docs.csc.fi/computing/running/array-jobs/
#
# Different Abaqus input files are identified by SLURM_ARRAY_TASK_ID variable
#

export OMP_NUM_THREADS=$SLURM_CPUS_PER_TASK
unset SLURM_GTIDS

module load abaqus/2022	

cd <your_run_directory>

CPUS_TOTAL=$(( $SLURM_NTASKS*$SLURM_CPUS_PER_TASK ))

mkdir tmp_$SLURM_JOB_ID_${SLURM_ARRAY_TASK_ID}

abq2022 job=${SLURM_ARRAY_TASK_ID}.inp cpus=$CPUS_TOTAL scratch=tmp_$SLURM_JOB_ID_${SLURM_ARRAY_TASK_ID} -verbose standard_parallel=all mp_mode=threads interactive


