#!/bin/bash -l
#SBATCH --job-name=abaTest
#SBATCH --error=%j_gpu.err
#SBATCH --output=%j_gpu.out
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=10
#SBATCH --mem-per-cpu=5000
#SBATCH --time=01:00:00
#SBATCH --partition=gpu
#SBATCH --gres=gpu:v100:1
#SBATCH --account=project_2007935

unset SLURM_GTIDS
module purge
module load abaqus/2022

cd $PWD

#Abaqus/Standard case
abq2022 job=s4b.inp fetch

mkdir tmp_$SLURM_JOB_ID

abq2022 job=s4b cpus=$SLURM_CPUS_PER_TASK gpus=1 scratch=tmp_$SLURM_JOB_ID interactive

