#!/bin/bash -l
#SBATCH --job-name=abaTest
#SBATCH --error=%j_N1_threads.err
#SBATCH --output=%j_N1_threads.out
#SBATCH --nodes=1
#SBATCH --ntasks=4
#SBATCH --cpus-per-task=10
#SBATCH --time=00:15:00
#SBATCH --partition=test
#SBATCH --account=project_2007935

#
# NOTICE.  Parallel run with Abaqus using threads mode is possible only on one node.
#

unset SLURM_GTIDS
module purge
module load abaqus/2022

export OMP_NUM_THREADS=$SLURM_CPUS_PER_TASK

cd $PWD

abq2022 job=e1.inp fetch

# env-file ++++++++++++++++++++++++++++++++++++

if [[ -f abaqus_v6.env ]]; then
    mv abaqus_v6.env abaqus_v6.env_previous
fi

# FOR ABAQUS RUNS ON > 1 NODE, MPI IMPLEMENTATION  IS IMPI !
echo "mp_mpi_implementation = IMPI" >> abaqus_v6.env
echo "mp_rsh_command = 'ssh -n -l %U %H %C'" >> abaqus_v6.env

NODE_LIST=$(scontrol show hostname ${SLURM_NODELIST} | sort -u)

mp_host_list="["
for host in ${NODE_LIST}; do
    mp_host_list="${mp_host_list}['$host', ${SLURM_CPUS_ON_NODE}],"
done

mp_host_list=$(echo ${mp_host_list} | sed -e "s/,$/]/")

echo "mp_host_list=${mp_host_list}"  >> abaqus_v6.env

# env-file ++++++++++++++++++++++++++++++++++++

mkdir tmp_$SLURM_JOB_ID

CPUS_TOTAL=$(( $SLURM_NTASKS*$SLURM_CPUS_PER_TASK ))

echo $CPUS_TOTAL

abq2022 job=e1 cpus=$CPUS_TOTAL scratch=tmp_$SLURM_JOB_ID -verbose standard_parallel=all mp_mode=threads interactive


